const fs=require('fs'),path=require('path'),assert=require('assert');
const puppeteer=require(path.resolve(__dirname,'../../../../../node_modules/puppeteer'));
const deck=path.resolve(__dirname,'../..');
const base=process.argv[2]||'http://127.0.0.1:8018/collections/external-presentations/calligraphy-generation/index.html';
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try{const page=await browser.newPage();await page.setViewport({width:1440,height:900});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});await page.goto(base,{waitUntil:'networkidle0'});await page.waitForFunction('window.Reveal && Reveal.isReady()');const initial=await page.evaluate(()=>({count:Reveal.getSlides().length,plugins:Object.keys(Reveal.getPlugins()),vertical:Reveal.getSlides().some(s=>s.parentElement.classList.contains('stack'))}));assert.equal(initial.count,17);assert(initial.vertical);await page.evaluate(()=>{const h=[...document.querySelector('.reveal .slides').children];if(JSON.stringify(h.map(s=>s.classList.contains('stack')?s.querySelectorAll(':scope > section').length:1))!==JSON.stringify([1,1,6,5,3,1]))throw Error('Incorrect part stacks');});await page.evaluate(()=>Reveal.configure({transition:'none'}));const slides=[];
for(let i=0;i<17;i++){await page.evaluate(i=>{const s=Reveal.getSlides()[i];const n=Reveal.getIndices(s);Reveal.slide(n.h,n.v);},i);await new Promise(r=>setTimeout(r,350));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(deck,`qa/screenshots/slide-${String(i+1).padStart(2,'0')}.png`)});slides.push(await page.evaluate(()=>{const s=Reveal.getCurrentSlide(),r=s.getBoundingClientRect();const els=[...s.querySelectorAll('img,table,.takeaway,.stats,.three-labels,.training-strip,h1,h2,h3')].filter(e=>!e.closest('aside'));return {title:s.querySelector('h1,h2').textContent,notes:!!s.querySelector('aside.notes'),images:[...s.querySelectorAll('img')].every(e=>e.complete&&e.naturalWidth>0),overflow:els.filter(e=>{const b=e.getBoundingClientRect();return b.bottom>r.bottom+2||b.right>r.right+2||b.left<r.left-2||b.right>window.innerWidth+2||b.left< -2||b.bottom>window.innerHeight+2}).map(e=>e.tagName+':'+(e.alt||e.textContent).slice(0,50))};}));}
await page.evaluate(()=>Reveal.slide(2,2));assert.equal(await page.$$eval('section.present:not(.stack) .glyph-table img',es=>es.length),160);await page.evaluate(()=>Reveal.slide(2,3));const cellCount=await page.$$eval('section.present:not(.stack) .glyph-table img',es=>es.length);assert.equal(cellCount,168);
await page.evaluate(()=>Reveal.slide(3,4));await new Promise(r=>setTimeout(r,350));await page.click('section.present:not(.stack) .figure-preview');assert(await page.$eval('.patent-viewer',e=>e.open));await page.keyboard.press('Escape');assert(await page.$eval('.patent-viewer',e=>!e.open));
await page.evaluate(()=>Reveal.slide(5,0));await new Promise(r=>setTimeout(r,350));await page.click('.patent-preview');assert(await page.$eval('.patent-viewer',e=>e.open));await page.click('.patent-viewer-close');assert(await page.$eval('.patent-viewer',e=>!e.open));
const people=await page.$$eval('.faculty-gallery figcaption',es=>es.map(e=>e.textContent));assert.deepEqual(people,['朱祥维','李颂元','王腾']);
await page.evaluate(()=>Reveal.slide(0));await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>Reveal.getIndices().h),1);await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>Reveal.getIndices().h),2);await page.evaluate(()=>Reveal.slide(2,0));await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>Reveal.getIndices().v),1);await page.keyboard.press('ArrowUp');assert.equal(await page.evaluate(()=>Reveal.getIndices().v),0);await page.keyboard.press('Escape');assert(await page.evaluate(()=>Reveal.isOverview()));await page.keyboard.press('Escape');assert(!await page.evaluate(()=>Reveal.isOverview()));
const report={initial,slides,errors,glyphCells:cellCount,people,figureViewer:true,patentViewer:true,navigation:true,overview:true};fs.writeFileSync(path.join(deck,'qa/reports/browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));assert.equal(errors.length,0);assert(slides.every(s=>s.notes&&s.images&&s.overflow.length===0));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
